all:
	pdflatex report.tex
	pdflatex report.tex
	pdflatex report-en.tex
	pdflatex report-en.tex
	pdflatex hermes-software.tex
	pdflatex hermes-software.tex

clean:
	rm -f report.aux report.out report.log report.toc report.pdf
	rm -f report-en.aux report-en.out report-en.log report-en.toc report-en.pdf
	rm -f hermes-software.aux hermes-software.out hermes-software.log hermes-software.toc hermes-software.pdf
