all:
	pdflatex report.tex
	pdflatex report.tex
	pdflatex report-en.tex
	pdflatex report-en.tex

clean:
	rm -f report.aux report.out report.log report.toc report.pdf
	rm -f report-en.aux report-en.out report-en.log report-en.toc report-en.pdf
