all:
	pdflatex report.tex
	pdflatex report.tex
	pdflatex equipment_en.tex
	pdflatex equipment_en.tex
	pdflatex hermes-software-en.tex
	pdflatex hermes-software-en.tex

clean:
	rm -f report.aux report.out report.log report.toc report.pdf
	rm -f equipment_en.aux equipment_en.out equipment_en.log equipment_en.toc equipment_en.pdf
	rm -f hermes-software-en.aux hermes-software-en.out hermes-software-en.log hermes-software-en.toc hermes-software-en.pdf
